# Project: Prototype
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Test.o
LINKOBJ  = Test.o
LIBS     = -L"D:/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -L"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_image-2.8.8/x86_64-w64-mingw32/lib" -L"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_ttf-2.24.0/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2-2.32.4/x86_64-w64-mingw32/lib" -L"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_image-2.8.8/x86_64-w64-mingw32/lib" -L"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_ttf-2.24.0/x86_64-w64-mingw32/lib" -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
INCS     = -I"D:/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2-2.32.4/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_image-2.8.8/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_ttf-2.24.0/x86_64-w64-mingw32/include"
CXXINCS  = -I"D:/Dev-Cpp/TDM-GCC-64/include" -I"D:/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2-2.32.4/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_image-2.8.8/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_ttf-2.24.0/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2-2.32.4/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_image-2.8.8/x86_64-w64-mingw32/include" -I"C:/Users/Aryan/OneDrive/Desktop/SDL_EXTERNALS/SDL2_ttf-2.24.0/x86_64-w64-mingw32/include"
BIN      = Prototype.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Test.o: Test.cpp
	$(CPP) -c Test.cpp -o Test.o $(CXXFLAGS)
